Allow reuse of the SyslogTcpSender for long-running programs that don't need an open connection
emertechie/SyslogNet pull request #25
Opened 2017-07-21 05:40 UTC by DWilches

- In the current implementation creation of the `SyslogTcpSender` object automatically connected to the server, now it's optional.
- The current implementation was calling multiple times to `Dispose`, which is used when we no longer need the object (MSDN docs are ambiguous about this, sometimes stating that the method is called when the object is no longer needed and that multiple invocations should be ignored, and in others stating the method can be used for preparing the object for reuse, so the proposed implementation plays safe in both cases).
- With these changes, one can create the `SyslogTcpSender` object and then before sending a batch of messages call `Reconnect`, and after sending them, call `Disconnect`. So the server can serve more clients than the number of connections available.

2017-07-27 21:35 UTC, grubman requested changes
I stated some minor changes before merging it

2017-07-27 21:35 UTC, grubman commented on SyslogNet.Client/Transport/SyslogTcpSender.cs
> +		public SyslogTcpSender(string hostname, int port, bool connect = true)
rename "connect" to "shouldAutoConnect"

2017-07-27 21:35 UTC, grubman commented on SyslogNet.Client/Transport/SyslogTcpSender.cs
> +				Connect();
Surround the Connect method with a block

2017-07-28 02:04 UTC, dwilches reviewed
Done with the changes

2017-07-28 02:04 UTC, DWilches commented on SyslogNet.Client/Transport/SyslogTcpSender.cs
> +		public SyslogTcpSender(string hostname, int port, bool connect = true)
Done

2017-07-28 02:04 UTC, DWilches commented on SyslogNet.Client/Transport/SyslogTcpSender.cs
> +				Connect();
Done

2017-07-29 15:14 UTC, merged